FILES= cyclic_scheduler executiontimes mixedscheduling overloaddetection overloaddetection2 periodictasks producerconsumer producerconsumer_prot producerconsumer_rndvzs producerconsumer_sem rms workingoverloaddetection

clean:
	rm -f $(FILES) *.o 
